### ISSUE TITLE
wormhole-solidity-sdk missing dependency 

### ISSUE THREAD

**Issue by Adg0** [wormhole-foundation/hello-wormhole#17]
The command `npm run build` has dependency issue. **wormhole-solidity-sdk** is not installed by the command.

I had to add `wormhole-solidity-sdk`, manually from the [repository](https://github.com/wormhole-foundation/wormhole-solidity-sdk) into `/lib/wormhole-solidity-sdk`

![image](https://github.com/wormhole-foundation/hello-wormhole/assets/86650590/464e647e-d4e3-4e3e-b164-e8b3901951d5)

**Comment by barnjamin** [comment]
I just tried from a fresh clone and this is working for me, have you made any changes locally? what version are you working with?

**Comment by Adg0** [comment]
I'm on node `v18.12.1` and npm `8.19.2`

**Comment by barnjamin** [comment]
Sorry I mean what version of this repo? is it a fresh clone?

**Comment by Adg0** [comment]
I think it was likely because of my git permissions on my drive
